version: "3"
services:
  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "10083:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml

