# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AuctionsPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, start_datetime=None, end_datetime=None):  # noqa: E501
        """AuctionsPostRequest - a model defined in OpenAPI

        :param name: The name of this AuctionsPostRequest.  # noqa: E501
        :type name: str
        :param start_datetime: The start_datetime of this AuctionsPostRequest.  # noqa: E501
        :type start_datetime: str
        :param end_datetime: The end_datetime of this AuctionsPostRequest.  # noqa: E501
        :type end_datetime: str
        """
        self.openapi_types = {
            'name': str,
            'start_datetime': str,
            'end_datetime': str
        }

        self.attribute_map = {
            'name': 'name',
            'start_datetime': 'start_datetime',
            'end_datetime': 'end_datetime'
        }

        self._name = name
        self._start_datetime = start_datetime
        self._end_datetime = end_datetime

    @classmethod
    def from_dict(cls, dikt) -> 'AuctionsPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The auctions_post_request of this AuctionsPostRequest.  # noqa: E501
        :rtype: AuctionsPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AuctionsPostRequest.


        :return: The name of this AuctionsPostRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AuctionsPostRequest.


        :param name: The name of this AuctionsPostRequest.
        :type name: str
        """

        self._name = name

    @property
    def start_datetime(self):
        """Gets the start_datetime of this AuctionsPostRequest.


        :return: The start_datetime of this AuctionsPostRequest.
        :rtype: str
        """
        return self._start_datetime

    @start_datetime.setter
    def start_datetime(self, start_datetime):
        """Sets the start_datetime of this AuctionsPostRequest.


        :param start_datetime: The start_datetime of this AuctionsPostRequest.
        :type start_datetime: str
        """

        self._start_datetime = start_datetime

    @property
    def end_datetime(self):
        """Gets the end_datetime of this AuctionsPostRequest.


        :return: The end_datetime of this AuctionsPostRequest.
        :rtype: str
        """
        return self._end_datetime

    @end_datetime.setter
    def end_datetime(self, end_datetime):
        """Sets the end_datetime of this AuctionsPostRequest.


        :param end_datetime: The end_datetime of this AuctionsPostRequest.
        :type end_datetime: str
        """

        self._end_datetime = end_datetime
