# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BidHistoryBid(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, price=None, bided_at=None):  # noqa: E501
        """BidHistoryBid - a model defined in OpenAPI

        :param price: The price of this BidHistoryBid.  # noqa: E501
        :type price: int
        :param bided_at: The bided_at of this BidHistoryBid.  # noqa: E501
        :type bided_at: str
        """
        self.openapi_types = {"price": int, "bided_at": str}

        self.attribute_map = {"price": "price", "bided_at": "bided_at"}

        self._price = price
        self._bided_at = bided_at

    @classmethod
    def from_dict(cls, dikt) -> "BidHistoryBid":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bid_history_bid of this BidHistoryBid.  # noqa: E501
        :rtype: BidHistoryBid
        """
        return util.deserialize_model(dikt, cls)

    @property
    def price(self):
        """Gets the price of this BidHistoryBid.


        :return: The price of this BidHistoryBid.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this BidHistoryBid.


        :param price: The price of this BidHistoryBid.
        :type price: int
        """

        self._price = price

    @property
    def bided_at(self):
        """Gets the bided_at of this BidHistoryBid.


        :return: The bided_at of this BidHistoryBid.
        :rtype: str
        """
        return self._bided_at

    @bided_at.setter
    def bided_at(self, bided_at):
        """Sets the bided_at of this BidHistoryBid.


        :param bided_at: The bided_at of this BidHistoryBid.
        :type bided_at: str
        """

        self._bided_at = bided_at
