# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.bid_history import BidHistory
from openapi_server import util

from openapi_server.models.bid_history import BidHistory  # noqa: E501

class BidHistorys(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bid_historys=None):  # noqa: E501
        """BidHistorys - a model defined in OpenAPI

        :param bid_historys: The bid_historys of this BidHistorys.  # noqa: E501
        :type bid_historys: List[BidHistory]
        """
        self.openapi_types = {
            'bid_historys': List[BidHistory]
        }

        self.attribute_map = {
            'bid_historys': 'bid_historys'
        }

        self._bid_historys = bid_historys

    @classmethod
    def from_dict(cls, dikt) -> 'BidHistorys':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bid_historys of this BidHistorys.  # noqa: E501
        :rtype: BidHistorys
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bid_historys(self):
        """Gets the bid_historys of this BidHistorys.


        :return: The bid_historys of this BidHistorys.
        :rtype: List[BidHistory]
        """
        return self._bid_historys

    @bid_historys.setter
    def bid_historys(self, bid_historys):
        """Sets the bid_historys of this BidHistorys.


        :param bid_historys: The bid_historys of this BidHistorys.
        :type bid_historys: List[BidHistory]
        """

        self._bid_historys = bid_historys
