# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BidHistoryItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, image_src=None, description=None, start_price=None):  # noqa: E501
        """BidHistoryItem - a model defined in OpenAPI

        :param id: The id of this BidHistoryItem.  # noqa: E501
        :type id: str
        :param name: The name of this BidHistoryItem.  # noqa: E501
        :type name: str
        :param image_src: The image_src of this BidHistoryItem.  # noqa: E501
        :type image_src: str
        :param description: The description of this BidHistoryItem.  # noqa: E501
        :type description: str
        :param start_price: The start_price of this BidHistoryItem.  # noqa: E501
        :type start_price: int
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'image_src': str,
            'description': str,
            'start_price': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'image_src': 'image_src',
            'description': 'description',
            'start_price': 'start_price'
        }

        self._id = id
        self._name = name
        self._image_src = image_src
        self._description = description
        self._start_price = start_price

    @classmethod
    def from_dict(cls, dikt) -> 'BidHistoryItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bid_history_item of this BidHistoryItem.  # noqa: E501
        :rtype: BidHistoryItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this BidHistoryItem.


        :return: The id of this BidHistoryItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BidHistoryItem.


        :param id: The id of this BidHistoryItem.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this BidHistoryItem.


        :return: The name of this BidHistoryItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BidHistoryItem.


        :param name: The name of this BidHistoryItem.
        :type name: str
        """

        self._name = name

    @property
    def image_src(self):
        """Gets the image_src of this BidHistoryItem.


        :return: The image_src of this BidHistoryItem.
        :rtype: str
        """
        return self._image_src

    @image_src.setter
    def image_src(self, image_src):
        """Sets the image_src of this BidHistoryItem.


        :param image_src: The image_src of this BidHistoryItem.
        :type image_src: str
        """

        self._image_src = image_src

    @property
    def description(self):
        """Gets the description of this BidHistoryItem.


        :return: The description of this BidHistoryItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BidHistoryItem.


        :param description: The description of this BidHistoryItem.
        :type description: str
        """

        self._description = description

    @property
    def start_price(self):
        """Gets the start_price of this BidHistoryItem.


        :return: The start_price of this BidHistoryItem.
        :rtype: int
        """
        return self._start_price

    @start_price.setter
    def start_price(self, start_price):
        """Sets the start_price of this BidHistoryItem.


        :param start_price: The start_price of this BidHistoryItem.
        :type start_price: int
        """

        self._start_price = start_price
