# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.auction_event import AuctionEvent
from openapi_server import util

from openapi_server.models.auction_event import AuctionEvent  # noqa: E501

class CommandsAuctionsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, events=None):  # noqa: E501
        """CommandsAuctionsResponse - a model defined in OpenAPI

        :param events: The events of this CommandsAuctionsResponse.  # noqa: E501
        :type events: List[AuctionEvent]
        """
        self.openapi_types = {
            'events': List[AuctionEvent]
        }

        self.attribute_map = {
            'events': 'events'
        }

        self._events = events

    @classmethod
    def from_dict(cls, dikt) -> 'CommandsAuctionsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The commands_auctions_response of this CommandsAuctionsResponse.  # noqa: E501
        :rtype: CommandsAuctionsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def events(self):
        """Gets the events of this CommandsAuctionsResponse.


        :return: The events of this CommandsAuctionsResponse.
        :rtype: List[AuctionEvent]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this CommandsAuctionsResponse.


        :param events: The events of this CommandsAuctionsResponse.
        :type events: List[AuctionEvent]
        """

        self._events = events
