# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class OpenAuction(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, start_date=None, end_date=None):  # noqa: E501
        """OpenAuction - a model defined in OpenAPI

        :param id: The id of this OpenAuction.  # noqa: E501
        :type id: int
        :param name: The name of this OpenAuction.  # noqa: E501
        :type name: str
        :param start_date: The start_date of this OpenAuction.  # noqa: E501
        :type start_date: datetime
        :param end_date: The end_date of this OpenAuction.  # noqa: E501
        :type end_date: datetime
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'start_date': datetime,
            'end_date': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'start_date': 'start_date',
            'end_date': 'end_date'
        }

        self._id = id
        self._name = name
        self._start_date = start_date
        self._end_date = end_date

    @classmethod
    def from_dict(cls, dikt) -> 'OpenAuction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The open_auction of this OpenAuction.  # noqa: E501
        :rtype: OpenAuction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this OpenAuction.


        :return: The id of this OpenAuction.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OpenAuction.


        :param id: The id of this OpenAuction.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this OpenAuction.


        :return: The name of this OpenAuction.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OpenAuction.


        :param name: The name of this OpenAuction.
        :type name: str
        """

        self._name = name

    @property
    def start_date(self):
        """Gets the start_date of this OpenAuction.


        :return: The start_date of this OpenAuction.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this OpenAuction.


        :param start_date: The start_date of this OpenAuction.
        :type start_date: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this OpenAuction.


        :return: The end_date of this OpenAuction.
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this OpenAuction.


        :param end_date: The end_date of this OpenAuction.
        :type end_date: datetime
        """

        self._end_date = end_date
