name: Deploy to AWS Lambda
on:
  push:
    branches:
      - master
    paths:
      - backend/main/**
      - .github/workflows/deploy-lambda.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Python Setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Lambda Build & Update
        run: |
          pip3 install awscli
          cd backend/main 
          pip install -r requirements.txt -t ./
          zip -r package.zip ./*
          aws lambda update-function-code --function-name BA-Integrated-backend --zip-file fileb://package.zip --publish
